### ISSUE TITLE
Logs and errors location

### ISSUE THREAD

**Issue by OroianRares** [samuelsimoes/chrome-extension-webpack-boilerplate#10]
Currently when I `console.log` something in chrome dev tools the browser locates the execute instruction line number in the whole bundle. (eg. `background.bundle.js:11383`). I would like to do something to make it locate the executed instruction in the original file that was copied in the bundle. (eg. `logger.js:16`)
Same problem with error line location.

What needs to be changed to make this happen?

**Comment by samuelsimoes** [comment]
I forgot source maps, sorry.

What you need to do is put on your `webpack.config.js` the [devtool](https://webpack.js.org/configuration/devtool/) config:

```
module.exports = {
  ...the rest of file omitted here...,
  devtool: 'cheap-module-eval-source-map'
}
```

I will update soon the boilerplate to already come with source maps.

Don't forget to disable the devtool when you build the production extension pack, because it causes performance issues that isn't problem in development, but is undesired in production.

**Comment by OroianRares** [comment]
Thank you!
