### ISSUE TITLE
Decouple webpack config for development and production build

### ISSUE THREAD

**Issue by rvasilev** [samuelsimoes/chrome-extension-webpack-boilerplate#40]
This should add some space for production build optimizations (uglify, code minimization, dead code elimination) and not to optimize development build.

Connected with #39 that will bundle css in single file, should be used for production build. Next we could add css tree shaking to remove unused css from bundle and minify it.

**Comment by samuelsimoes** [comment]
This separation for this boilerplate is really worth? Just place the production compile configs in `webpack.config.js` doesn't do the work?

I didn't included uglify and code minimization by default because I don't think that these things are critically necessary to an extension, where these assets won't be loaded from the network, and the extension is downloaded from Chrome Store compressed.

Don't take me wrong, I just want to keep this boilerplate as minimal possible to make sure that it is a compressive example how to start a Chrome extension with Webpack, the focus isn't to create the most complete boilerplate.

About the CSS, I didn't analyze your PR yet, but is critical to include all CS in a single file? But I agree that the CSS must be separated from the javascript bundle because screen flickering, but we discuss this on the PR.

**Comment by samuelsimoes** [comment]
Closing by the lack of activity.
